'use client';

import { useEffect, useRef, useState } from 'react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { BarChart3, Download, FileText, Calendar, Filter, Plus, MoreVertical, Search } from 'lucide-react';
import { useAppSelector } from '@/store/hooks';
import { reports } from '@/lib/mock-data';
import gsap from 'gsap';
import { useToast } from '@/components/ui/ToastProvider';
import { Dialog, DialogTitle, DialogContent, DialogActions, Menu, MenuItem } from '@mui/material';

export default function ReportsPage() {
  const { tenant } = useAppSelector((state) => state.auth);
  const containerRef = useRef<HTMLDivElement>(null);
  const { showToast } = useToast();
  
  // Base reports matching tenant
  const [baseReports, setBaseReports] = useState(reports.filter(r => r.tenantId === tenant?.id));
  const [localReports, setLocalReports] = useState(baseReports);

  // Dialogs
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isSearchDialogOpen, setIsSearchDialogOpen] = useState(false);
  
  const [reportName, setReportName] = useState('');
  const [reportType, setReportType] = useState('Compliance Assessment');

  const [searchQuery, setSearchQuery] = useState('');

  // Context Menu Anchors
  const [menuAnchorEl, setMenuAnchorEl] = useState<null | HTMLElement>(null);
  const [selectedReport, setSelectedReport] = useState<any>(null);

  useEffect(() => {
    if (containerRef.current) {
      const rows = containerRef.current.querySelectorAll('tbody tr');
      gsap.fromTo(rows, 
        { y: 10, opacity: 0 },
        { y: 0, opacity: 1, duration: 0.4, stagger: 0.05, ease: 'power2.out' }
      );
    }
  }, [localReports.length]);

  const handleCreateReport = () => {
    if (!reportName) {
      showToast('Report name is required.', 'error');
      return;
    }
    const newReport = {
      id: `rep-${Math.floor(Math.random() * 90000)}`,
      name: reportName,
      type: reportType,
      date: 'Current Processing',
      status: 'ready' as any,
      tenantId: tenant?.id || 't-1'
    };
    
    showToast('Queuing report intelligence engine...', 'info');
    setIsDialogOpen(false);
    
    setTimeout(() => {
      const updated = [newReport, ...baseReports];
      setBaseReports(updated);
      setLocalReports(updated);
      setReportName('');
      showToast(`Report '${newReport.name}' generated successfully.`, 'success');
    }, 1500);
  };

  const handleExecuteSearch = () => {
    if (!searchQuery.trim()) {
      setLocalReports(baseReports);
    } else {
      const q = searchQuery.toLowerCase();
      setLocalReports(baseReports.filter(r => 
        r.name.toLowerCase().includes(q) || r.type.toLowerCase().includes(q)
      ));
    }
    setIsSearchDialogOpen(false);
  };

  const handleDownload = (report: any) => {
    showToast(`Assembling dataset for ${report.name}...`, 'info');
    setTimeout(() => {
      const content = `Report ID: ${report.id}\nName: ${report.name}\nType: ${report.type}\nStatus: ${report.status}\n\nMetrics generated by ShieldOS Intelligence Layer.`;
      const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
      const link = document.createElement('a');
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', `${report.name.replace(/\s+/g, '_')}.txt`);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      showToast('Download complete.', 'success');
    }, 1000);
  };

  const handleMenuOpen = (e: React.MouseEvent<HTMLButtonElement>, report: any) => {
    setMenuAnchorEl(e.currentTarget);
    setSelectedReport(report);
  };

  const handleMenuClose = () => {
    setMenuAnchorEl(null);
    setSelectedReport(null);
  };

  const handleDeleteReport = () => {
    if (selectedReport) {
      const updated = baseReports.filter(r => r.id !== selectedReport.id);
      setBaseReports(updated);
      setLocalReports(updated);
      showToast('Report deleted successfully.', 'warning');
    }
    handleMenuClose();
  };

  const handleArchiveReport = () => {
    if (selectedReport) {
      showToast(`Report ${selectedReport.name} archived.`, 'info');
    }
    handleMenuClose();
  };

  return (
    <DashboardLayout title="Reporting & Insights">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2.5rem' }}>
        <div>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.875rem' }}>Generate and manage security performance and compliance reports.</p>
        </div>
        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button onClick={() => setIsSearchDialogOpen(true)} className="btn btn-outline" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Search size={18} />
            <span>Search Reports</span>
          </button>
          <button onClick={() => setIsDialogOpen(true)} className="btn btn-primary" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Plus size={18} />
            <span>Create Custom Report</span>
          </button>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1.5rem', marginBottom: '2rem' }}>
        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1rem', border: '1px solid var(--border)' }}>
          <div style={{ padding: '0.75rem', background: 'var(--primary-light)', color: 'var(--primary)', borderRadius: 'var(--radius)', width: 'fit-content' }}>
            <BarChart3 size={20} />
          </div>
          <div>
            <h4 style={{ fontWeight: 700, fontSize: '1rem', marginBottom: '0.25rem' }}>Automated Reports</h4>
            <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', lineHeight: '1.5' }}>Scheduled reports are sent every Monday at 08:00 UTC to all administrators.</p>
          </div>
        </div>
        
        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1rem', border: '1px solid var(--border)' }}>
          <div style={{ padding: '0.75rem', background: 'rgba(245, 158, 11, 0.1)', color: 'var(--risk-medium)', borderRadius: 'var(--radius)', width: 'fit-content' }}>
            <Calendar size={20} />
          </div>
          <div>
            <h4 style={{ fontWeight: 700, fontSize: '1rem', marginBottom: '0.25rem' }}>Retention Policy</h4>
            <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', lineHeight: '1.5' }}>Reports are persisted for 365 days unless otherwise specified in settings.</p>
          </div>
        </div>

        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1rem', border: '1px solid var(--border)' }}>
          <div style={{ padding: '0.75rem', background: 'rgba(37, 99, 235, 0.1)', color: 'var(--risk-low)', borderRadius: 'var(--radius)', width: 'fit-content' }}>
            <Filter size={20} />
          </div>
          <div>
            <h4 style={{ fontWeight: 700, fontSize: '1rem', marginBottom: '0.25rem' }}>Custom Filters</h4>
            <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', lineHeight: '1.5' }}>Create specialized views by filtering on specific data tags or threat categories.</p>
          </div>
        </div>
      </div>

      <div ref={containerRef} className="card" style={{ padding: 0, overflow: 'hidden', border: '1px solid var(--border)' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
          <thead style={{ background: 'var(--bg-light)', borderBottom: '1px solid var(--border)' }}>
            <tr>
              <th style={{ padding: '1.25rem 1rem', fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Report Name</th>
              <th style={{ padding: '1.25rem 1rem', fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Type</th>
              <th style={{ padding: '1.25rem 1rem', fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Date Range</th>
              <th style={{ padding: '1.25rem 1rem', fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Status</th>
              <th style={{ padding: '1.25rem 1rem' }}></th>
            </tr>
          </thead>
          <tbody>
            {localReports.length > 0 ? (
              localReports.map((report) => (
                <tr key={report.id} style={{ borderBottom: '1px solid var(--border)', transition: 'background 0.2s' }} onMouseEnter={(e) => e.currentTarget.style.background = 'var(--bg-light)'} onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}>
                  <td style={{ padding: '1.25rem 1rem' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                      <div style={{ padding: '0.5rem', background: 'var(--bg-light)', borderRadius: 'var(--radius)', border: '1px solid var(--border)' }}>
                        <FileText size={18} color="var(--text-secondary)" />
                      </div>
                      <span style={{ fontWeight: 600, fontSize: '0.875rem', color: 'var(--text-primary)' }}>{report.name}</span>
                    </div>
                  </td>
                  <td style={{ padding: '1.25rem 1rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
                    <span style={{ padding: '0.25rem 0.5rem', borderRadius: '4px', background: 'var(--bg-light)', border: '1px solid var(--border)', fontSize: '0.75rem' }}>{report.type}</span>
                  </td>
                  <td style={{ padding: '1.25rem 1rem', fontSize: '0.875rem', color: 'var(--text-muted)' }}>{report.date}</td>
                  <td style={{ padding: '1.25rem 1rem' }}>
                    <span style={{ 
                      padding: '0.375rem 0.75rem', 
                      borderRadius: '999px', 
                      fontSize: '0.7rem', 
                      fontWeight: 800,
                      letterSpacing: '0.02em',
                      background: report.status === 'ready' ? 'rgba(37, 99, 235, 0.1)' : 'rgba(245, 158, 11, 0.1)',
                      color: report.status === 'ready' ? 'var(--risk-low)' : 'var(--risk-medium)'
                    }}>
                      {report.status.toUpperCase()}
                    </span>
                  </td>
                  <td style={{ padding: '1.25rem 1rem', textAlign: 'right' }}>
                    <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.5rem' }}>
                      <button onClick={() => handleDownload(report)} style={{ background: 'none', border: 'none', color: 'var(--primary)', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '0.25rem', fontSize: '0.875rem', padding: '0.5rem', borderRadius: 'var(--radius)', transition: 'background 0.2s' }} onMouseEnter={(e)=>e.currentTarget.style.background = 'var(--primary-light)'} onMouseLeave={(e)=>e.currentTarget.style.background = 'transparent'}>
                        <Download size={16} />
                        Download
                      </button>
                      <button onClick={(e) => handleMenuOpen(e, report)} style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '0.5rem' }}>
                        <MoreVertical size={18} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={5} style={{ padding: '6rem', textAlign: 'center', color: 'var(--text-muted)' }}>
                  <FileText size={48} style={{ marginBottom: '1rem', opacity: 0.2 }} />
                  <p style={{ fontSize: '1rem', fontWeight: 500 }}>No reports found.</p>
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* CREATE REPORT DIALOG */}
      <Dialog 
        open={isDialogOpen} 
        onClose={() => setIsDialogOpen(false)}
        PaperProps={{ style: { background: 'var(--bg-dark)', color: 'var(--text-primary)', border: '1px solid var(--border)', fontFamily: 'var(--font-sans)', minWidth: '400px' } }}
      >
        <DialogTitle style={{ borderBottom: '1px solid var(--border)', fontSize: '1.125rem', fontWeight: 600 }}>Create Report Request</DialogTitle>
        <DialogContent style={{ paddingTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>Report Name</label>
            <input 
              type="text"
              value={reportName}
              onChange={(e) => setReportName(e.target.value)}
              placeholder="e.g. Q3 Access Audit"
              style={{ width: '100%', padding: '0.75rem', background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: '4px', color: 'var(--text-primary)', outline: 'none' }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>Target Schema</label>
            <select 
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
              style={{ width: '100%', padding: '0.75rem', background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: '4px', color: 'var(--text-primary)', outline: 'none' }}
            >
              <option value="Compliance Assessment">Compliance Assessment (SOC2)</option>
              <option value="Threat Intelligence">Threat Intelligence (STIX)</option>
              <option value="User Activity Log">User Activity Log</option>
            </select>
          </div>
        </DialogContent>
        <DialogActions style={{ borderTop: '1px solid var(--border)', padding: '1rem' }}>
          <button onClick={() => setIsDialogOpen(false)} className="btn btn-outline">Cancel</button>
          <button onClick={handleCreateReport} className="btn btn-primary">Generate</button>
        </DialogActions>
      </Dialog>

      {/* SEARCH REPORTS DIALOG */}
      <Dialog 
        open={isSearchDialogOpen} 
        onClose={() => setIsSearchDialogOpen(false)}
        PaperProps={{ style: { background: 'var(--bg-dark)', color: 'var(--text-primary)', border: '1px solid var(--border)', fontFamily: 'var(--font-sans)', minWidth: '400px' } }}
      >
        <DialogTitle style={{ borderBottom: '1px solid var(--border)', fontSize: '1.125rem', fontWeight: 600 }}>Search Reports</DialogTitle>
        <DialogContent style={{ paddingTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>Search Terms</label>
            <input 
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Filter by name or type..."
              style={{ width: '100%', padding: '0.75rem', background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: '4px', color: 'var(--text-primary)', outline: 'none' }}
            />
          </div>
        </DialogContent>
        <DialogActions style={{ borderTop: '1px solid var(--border)', padding: '1rem' }}>
          <button onClick={() => { setSearchQuery(''); setLocalReports(baseReports); setIsSearchDialogOpen(false); }} className="btn btn-outline">Clear</button>
          <button onClick={handleExecuteSearch} className="btn btn-primary">Search</button>
        </DialogActions>
      </Dialog>

      {/* REPORT OPTIONS MENU */}
      <Menu
        anchorEl={menuAnchorEl}
        open={Boolean(menuAnchorEl)}
        onClose={handleMenuClose}
        PaperProps={{
          style: {
            background: 'var(--bg-card)',
            border: '1px solid var(--border)',
            boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.5)',
            color: 'var(--text-primary)'
          }
        }}
      >
        <MenuItem onClick={handleArchiveReport} style={{ fontSize: '0.875rem', fontFamily: 'var(--font-sans)' }}>Archive Report</MenuItem>
        <MenuItem onClick={handleDeleteReport} style={{ fontSize: '0.875rem', color: 'var(--risk-high)', fontFamily: 'var(--font-sans)' }}>Delete Report</MenuItem>
      </Menu>

    </DashboardLayout>
  );
}
