'use client';

import { useEffect, useRef, useState } from 'react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { BarChart3, Download, FileText, Calendar, Filter, Plus, MoreVertical, Search } from 'lucide-react';
import { useAppSelector } from '@/store/hooks';
import { reports } from '@/lib/mock-data';
import gsap from 'gsap';
import { useToast } from '@/components/ui/ToastProvider';
import { Dialog, DialogTitle, DialogContent, DialogActions, Menu, MenuItem, Select, FormControl, InputLabel } from '@mui/material';
import { Pagination } from '@/components/ui/Pagination';

export default function ReportsPage() {
  const { tenant } = useAppSelector((state) => state.auth);
  const containerRef = useRef<HTMLDivElement>(null);
  const { showToast } = useToast();
  
  // Base reports matching tenant
  const [baseReports, setBaseReports] = useState(reports.filter(r => r.tenantId === tenant?.id));
  const [localReports, setLocalReports] = useState(baseReports);

  // Pagination State
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 8;

  // Dialogs
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isSearchDialogOpen, setIsSearchDialogOpen] = useState(false);
  
  const [reportName, setReportName] = useState('');
  const [reportType, setReportType] = useState('Compliance Assessment');

  const [searchQuery, setSearchQuery] = useState('');

  // Context Menu Anchors
  const [menuAnchorEl, setMenuAnchorEl] = useState<null | HTMLElement>(null);
  const [selectedReport, setSelectedReport] = useState<any>(null);

  useEffect(() => {
    if (containerRef.current) {
      const rows = containerRef.current.querySelectorAll('tbody tr');
      gsap.fromTo(rows, 
        { y: 10, opacity: 0 },
        { y: 0, opacity: 1, duration: 0.4, stagger: 0.05, ease: 'power2.out' }
      );
    }
  }, [localReports.length, currentPage]);

  const handleCreateReport = () => {
    if (!reportName) {
      showToast('Report name is required.', 'error');
      return;
    }
    const newReport = {
      id: `rep-${Math.floor(Math.random() * 90000)}`,
      name: reportName,
      type: reportType,
      date: 'Current Processing',
      status: 'ready' as any,
      tenantId: tenant?.id || 't-1'
    };
    
    showToast('Queuing report intelligence engine...', 'info');
    setIsDialogOpen(false);
    
    setTimeout(() => {
      const updated = [newReport, ...baseReports];
      setBaseReports(updated);
      setLocalReports(updated);
      setReportName('');
      showToast(`Report '${newReport.name}' generated successfully.`, 'success');
    }, 1500);
  };

  const handleExecuteSearch = () => {
    if (!searchQuery.trim()) {
      setLocalReports(baseReports);
    } else {
      const q = searchQuery.toLowerCase();
      setLocalReports(baseReports.filter(r => 
        r.name.toLowerCase().includes(q) || r.type.toLowerCase().includes(q)
      ));
    }
    setCurrentPage(1);
    setIsSearchDialogOpen(false);
  };

  // Paginated View
  const paginatedReports = localReports.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );
  const totalPages = Math.ceil(localReports.length / itemsPerPage);

  const handleDownload = (report: any) => {
    showToast(`Assembling dataset for ${report.name}...`, 'info');
    setTimeout(() => {
      const content = `Report ID: ${report.id}\nName: ${report.name}\nType: ${report.type}\nStatus: ${report.status}\n\nMetrics generated by Ostec Intelligence Layer.`;
      const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
      const link = document.createElement('a');
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', `${report.name.replace(/\s+/g, '_')}.txt`);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      showToast('Download complete.', 'success');
    }, 1000);
  };

  const handleMenuOpen = (e: React.MouseEvent<HTMLButtonElement>, report: any) => {
    setMenuAnchorEl(e.currentTarget);
    setSelectedReport(report);
  };

  const handleMenuClose = () => {
    setMenuAnchorEl(null);
    setSelectedReport(null);
  };

  const handleDeleteReport = () => {
    if (selectedReport) {
      const updated = baseReports.filter(r => r.id !== selectedReport.id);
      setBaseReports(updated);
      setLocalReports(updated);
      showToast('Report deleted successfully.', 'warning');
    }
    handleMenuClose();
  };

  const handleArchiveReport = () => {
    if (selectedReport) {
      showToast(`Report ${selectedReport.name} archived.`, 'info');
    }
    handleMenuClose();
  };

  return (
    <DashboardLayout title="Log Center & Intelligence">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }} className="mobile-stack">
        <div>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.75rem', fontWeight: 600 }}>Security event logs and regulatory compliance documentation portal.</p>
        </div>
        <div style={{ display: 'flex', gap: '0.6rem' }}>
          <button onClick={() => setIsSearchDialogOpen(true)} className="btn btn-outline" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.7rem', padding: '0.4rem 0.8rem' }}>
            <Search size={14} />
            <span>Search</span>
          </button>
          <button onClick={() => setIsDialogOpen(true)} className="btn btn-primary" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.7rem', padding: '0.4rem 0.8rem' }}>
            <Plus size={14} />
            <span>Generate Report</span>
          </button>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem', marginBottom: '1.5rem' }} className="grid-responsive-metrics">
        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', background: 'var(--bg-dark-card)' }}>
          <div style={{ padding: '0.5rem', background: 'var(--primary-light)', color: 'var(--primary)', borderRadius: '4px', width: 'fit-content' }}>
            <BarChart3 size={18} />
          </div>
          <div>
            <h4 style={{ fontWeight: 800, fontSize: '0.75rem', color: 'var(--text-primary)', textTransform: 'uppercase', marginBottom: '0.2rem' }}>Automation</h4>
            <p style={{ fontSize: '0.65rem', color: 'var(--text-muted)', lineHeight: '1.4' }}>Scheduled cadence: Weekly (Mon 08:00 UTC).</p>
          </div>
        </div>
        
        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', background: 'var(--bg-dark-card)' }}>
          <div style={{ padding: '0.5rem', background: 'rgba(245, 158, 11, 0.1)', color: 'var(--risk-medium)', borderRadius: '4px', width: 'fit-content' }}>
            <Calendar size={18} />
          </div>
          <div>
            <h4 style={{ fontWeight: 800, fontSize: '0.75rem', color: 'var(--text-primary)', textTransform: 'uppercase', marginBottom: '0.2rem' }}>Retention</h4>
            <p style={{ fontSize: '0.65rem', color: 'var(--text-muted)', lineHeight: '1.4' }}>Technical data persisted for 365 days.</p>
          </div>
        </div>

        <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', background: 'var(--bg-dark-card)' }}>
          <div style={{ padding: '0.5rem', background: 'rgba(16, 185, 129, 0.1)', color: 'var(--risk-low)', borderRadius: '4px', width: 'fit-content' }}>
            <Filter size={18} />
          </div>
          <div>
            <h4 style={{ fontWeight: 800, fontSize: '0.75rem', color: 'var(--text-primary)', textTransform: 'uppercase', marginBottom: '0.2rem' }}>Audit Trail</h4>
            <p style={{ fontSize: '0.65rem', color: 'var(--text-muted)', lineHeight: '1.4' }}>Immutable logging active for all exports.</p>
          </div>
        </div>
      </div>

      <div ref={containerRef} className="card" style={{ padding: 0, overflow: 'hidden', background: 'var(--bg-dark-card)' }}>
        <div style={{ padding: '0.75rem 1rem', borderBottom: '1px solid var(--border)', background: 'var(--bg-light)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <h3 style={{ fontSize: '0.75rem', fontWeight: 800, textTransform: 'uppercase', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <FileText size={14} /> Document Registry
          </h3>
          <div style={{ fontSize: '0.6rem', color: 'var(--text-muted)', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
             Page {currentPage} of {totalPages}
          </div>
        </div>
        <div className="responsive-table-container">
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }} className="table-min-width">
            <thead style={{ background: 'var(--bg-light)', borderBottom: '1px solid var(--border)' }}>
              <tr>
                <th style={{ padding: '0.6rem 1rem', fontSize: '0.65rem', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Report Context</th>
                <th style={{ padding: '0.6rem 1rem', fontSize: '0.65rem', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Classification</th>
                <th style={{ padding: '0.6rem 1rem', fontSize: '0.65rem', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Temporal Range</th>
                <th style={{ padding: '0.6rem 1rem', fontSize: '0.65rem', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Integrity</th>
                <th style={{ padding: '0.6rem 1rem' }}></th>
              </tr>
            </thead>
            <tbody>
              {paginatedReports.length > 0 ? (
                paginatedReports.map((report) => (
                  <tr key={report.id} className="hover-high-density" style={{ borderBottom: '1px solid var(--border)', transition: 'background 0.1s' }}>
                    <td style={{ padding: '0.5rem 1rem' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                       <FileText size={16} color="var(--text-muted)" />
                        <div style={{ display: 'flex', flexDirection: 'column' }}>
                          <span style={{ fontWeight: 700, fontSize: '0.8rem', color: 'var(--text-primary)' }}>{report.name}</span>
                          <span className="font-mono" style={{ fontSize: '0.6rem', color: 'var(--text-muted)' }}>{report.id}</span>
                        </div>
                      </div>
                    </td>
                    <td style={{ padding: '0.5rem 1rem' }}>
                      <span style={{ padding: '0.15rem 0.4rem', borderRadius: '2px', background: 'var(--bg-light)', border: '1px solid var(--border)', fontSize: '0.6rem', fontWeight: 700, color: 'var(--text-secondary)' }}>{report.type}</span>
                    </td>
                    <td style={{ padding: '0.5rem 1rem', fontSize: '0.7rem', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>{report.date}</td>
                    <td style={{ padding: '0.5rem 1rem' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                        <div style={{ 
                          width: '6px', 
                          height: '6px', 
                          borderRadius: '50%',
                          backgroundColor: report.status === 'ready' ? 'var(--risk-low)' : 'var(--risk-medium)',
                        }}></div>
                        <span style={{ fontSize: '0.65rem', fontWeight: 800, color: 'var(--text-primary)', textTransform: 'uppercase' }}>
                          {report.status}
                        </span>
                      </div>
                    </td>
                    <td style={{ padding: '0.5rem 1rem', textAlign: 'right' }}>
                      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.25rem' }}>
                        <button onClick={() => handleDownload(report)} style={{ background: 'none', border: 'none', color: 'var(--primary)', cursor: 'pointer', padding: '0.4rem', borderRadius: '4px' }} className="btn-icon-hover">
                          <Download size={14} />
                        </button>
                        <button onClick={(e) => handleMenuOpen(e, report)} style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '0.4rem' }}>
                          <MoreVertical size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={5} style={{ padding: '4rem', textAlign: 'center', color: 'var(--text-muted)' }}>
                    <FileText size={32} style={{ marginBottom: '0.75rem', opacity: 0.2 }} />
                    <p style={{ fontSize: '0.8rem', fontWeight: 500 }}>Empty registry.</p>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
        <Pagination currentPage={currentPage} totalPages={totalPages} onPageChange={setCurrentPage} />
      </div>

      <Dialog open={isDialogOpen} onClose={() => setIsDialogOpen(false)} PaperProps={{ style: { background: 'var(--bg-dark)', color: 'var(--text-primary)', border: '1px solid var(--border)', minWidth: '400px' } }}>
        <DialogTitle style={{ borderBottom: '1px solid var(--border)' }}>Create Report Request</DialogTitle>
        <DialogContent style={{ paddingTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>Report Name</label>
            <input 
              type="text"
              value={reportName}
              onChange={(e) => setReportName(e.target.value)}
              style={{ width: '100%', padding: '0.75rem', background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: '4px', color: 'var(--text-primary)' }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>Target Schema</label>
            <Select 
              value={reportType} 
              onChange={(e) => setReportType(e.target.value as string)}
              fullWidth
              sx={{ background: 'var(--bg-card)', color: 'var(--text-primary)', '.MuiOutlinedInput-notchedOutline': { borderColor: 'var(--border)' } }}
            >
              <MenuItem value="Compliance Assessment">Compliance Assessment (SOC2)</MenuItem>
              <MenuItem value="Threat Intelligence">Threat Intelligence (STIX)</MenuItem>
              <MenuItem value="User Activity Log">User Activity Log</MenuItem>
            </Select>
          </div>
        </DialogContent>
        <DialogActions style={{ borderTop: '1px solid var(--border)', padding: '1rem' }}>
          <button onClick={() => setIsDialogOpen(false)} className="btn btn-outline">Cancel</button>
          <button onClick={handleCreateReport} className="btn btn-primary">Generate</button>
        </DialogActions>
      </Dialog>

      <Dialog open={isSearchDialogOpen} onClose={() => setIsSearchDialogOpen(false)} PaperProps={{ style: { background: 'var(--bg-dark)', color: 'var(--text-primary)', border: '1px solid var(--border)', minWidth: '400px' } }}>
        <DialogTitle style={{ borderBottom: '1px solid var(--border)' }}>Search Reports</DialogTitle>
        <DialogContent style={{ paddingTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>Search Terms</label>
            <input 
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={{ width: '100%', padding: '0.75rem', background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: '4px', color: 'var(--text-primary)' }}
            />
          </div>
        </DialogContent>
        <DialogActions style={{ borderTop: '1px solid var(--border)', padding: '1rem' }}>
          <button onClick={() => { setSearchQuery(''); setLocalReports(baseReports); setIsSearchDialogOpen(false); }} className="btn btn-outline">Clear</button>
          <button onClick={handleExecuteSearch} className="btn btn-primary">Search</button>
        </DialogActions>
      </Dialog>

      <Menu
        anchorEl={menuAnchorEl}
        open={Boolean(menuAnchorEl)}
        onClose={handleMenuClose}
        PaperProps={{ style: { background: 'var(--bg-card)', border: '1px solid var(--border)', color: 'var(--text-primary)' } }}
      >
        <MenuItem onClick={handleArchiveReport} style={{ fontSize: '0.875rem' }}>Archive Report</MenuItem>
        <MenuItem onClick={handleDeleteReport} style={{ fontSize: '0.875rem', color: 'var(--risk-high)' }}>Delete Report</MenuItem>
      </Menu>
    </DashboardLayout>
  );
}
