'use client';

import { useAppSelector } from '@/store/hooks';
import { reports } from '@/lib/mock-data';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { FileText, Download, Share2, Calendar, FileBarChart, PieChart, TrendingDown } from 'lucide-react';
import { useState } from 'react';
import { Dialog, DialogTitle, DialogContent, DialogActions, Select, MenuItem } from '@mui/material';

export default function BoardReportsPage() {
  const { tenant } = useAppSelector((state) => state.auth);
  
  const [localReports, setLocalReports] = useState(reports);
  const tenantReports = localReports.filter(r => r.tenantId === tenant?.id);
  
  const [toast, setToast] = useState('');
  const [isGenerateOpen, setIsGenerateOpen] = useState(false);
  const [newReportName, setNewReportName] = useState('');
  const [newReportType, setNewReportType] = useState('Executive');
  
  const [isScheduleOpen, setIsScheduleOpen] = useState(false);

  const triggerToast = (action: string) => {
    setToast(action);
    setTimeout(() => setToast(''), 3000);
  };

  const handleGenerate = () => {
    if (!newReportName) {
      triggerToast('Please provide a report name.');
      return;
    }
    const newReport = {
      id: `rep-${Math.random().toString(36).substring(2, 6)}`,
      name: newReportName,
      date: new Date().toLocaleDateString('en-US', { month: 'short', year: 'numeric' }),
      type: newReportType,
      status: 'ready',
      tenantId: tenant?.id || 't1',
      summary: 'Automatically generated AI risk summary showing stable environment metrics.'
    };
    
    setLocalReports([newReport, ...localReports]);
    setIsGenerateOpen(false);
    setNewReportName('');
    triggerToast('Report successfully generated.');
  };

  const handleDownload = (report: any) => {
    const textContent = `
SHIELD OS SECURE REPORT EXPORT
-----------------------------------
Report Name: ${report.name}
Date: ${report.date}
Type: ${report.type}
Client: ${tenant?.name}

SUMMARY:
${report.summary || 'Standard compliance evaluation completed.'}

*This document was auto-generated by ShieldOS reporting.*
`;
    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.name.replace(/\s+/g, '_')}_Report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    triggerToast('Downloading PDF / TXT bundle...');
  };

  const handleShare = (report: any) => {
    const subject = encodeURIComponent(`ShieldOS Report: ${report.name}`);
    const body = encodeURIComponent(`Please review the latest ${report.type} report generated on ${report.date}.\n\nSummary:\n${report.summary}`);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  return (
    <DashboardLayout title="Executive Board Reports">
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', paddingBottom: '3rem', position: 'relative' }}>
        
        {toast && (
          <div style={{ position: 'fixed', top: '20px', left: '50%', transform: 'translateX(-50%)', background: 'var(--primary)', color: 'white', padding: '1rem', borderRadius: '8px', zIndex: 1000, boxShadow: '0 4px 12px rgba(0,0,0,0.5)', fontWeight: 600 }}>
            {toast}
          </div>
        )}

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', flexWrap: 'wrap', gap: '1rem' }}>
          <div>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--text-primary)', margin: 0 }}>Executive Storytelling</h2>
            <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)' }}>High-value, automated plain-english summaries for board and executive committees.</p>
          </div>
          <button className="btn btn-primary" onClick={() => setIsGenerateOpen(true)}>
            + Generate Report
          </button>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))', gap: '1.5rem' }}>
          {tenantReports.map(report => (
            <div key={report.id} className="card" style={{ padding: '0', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
              
              <div style={{ background: 'var(--bg-light)', padding: '1.5rem', borderBottom: '1px solid var(--border)' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                  <span className="badge" style={{ background: 'var(--primary-light)', color: 'var(--primary)' }}>{report.type}</span>
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', fontWeight: 600 }}>{report.date}</span>
                </div>
                <h3 style={{ fontSize: '1.2rem', fontWeight: 900, color: 'var(--text-primary)', margin: '0 0 0.5rem 0' }}>{report.name}</h3>
                
                {report.summary && (
                  <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: 1.5, background: 'rgba(255,255,255,0.05)', padding: '0.75rem', borderRadius: '4px', borderLeft: '3px solid var(--primary)' }}>
                    "{report.summary}"
                  </p>
                )}
              </div>

              {/* Mock Mini Visual */}
              <div style={{ padding: '1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--bg-card)', minHeight: '120px' }}>
                {report.type === 'Executive' ? (
                  <div style={{ display: 'flex', gap: '2rem', alignItems: 'center' }}>
                    <TrendingDown size={40} color="var(--risk-low)" />
                    <div>
                      <h4 style={{ fontSize: '1.5rem', fontWeight: 900, margin: 0 }}>-12%</h4>
                      <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Month over month risk</span>
                    </div>
                  </div>
                ) : report.type === 'Operational' ? (
                   <FileBarChart size={60} color="var(--text-muted)" style={{ opacity: 0.5 }} />
                ) : (
                   <PieChart size={60} color="var(--text-muted)" style={{ opacity: 0.5 }} />
                )}
              </div>

              <div style={{ padding: '1rem', borderTop: '1px solid var(--border)', display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '0.5rem', background: 'var(--bg-card)' }}>
                 <button onClick={() => handleDownload(report)} className="btn btn-outline" style={{ fontSize: '0.7rem', padding: '0.4rem', display: 'flex', gap: '0.4rem' }}>
                   <Download size={14} /> PDF
                 </button>
                 <button onClick={() => handleShare(report)} className="btn btn-outline" style={{ fontSize: '0.7rem', padding: '0.4rem', display: 'flex', gap: '0.4rem' }}>
                   <Share2 size={14} /> Share
                 </button>
                 <button onClick={() => setIsScheduleOpen(true)} className="btn btn-outline" style={{ fontSize: '0.7rem', padding: '0.4rem', display: 'flex', gap: '0.4rem' }}>
                   <Calendar size={14} /> Schedule
                 </button>
              </div>

            </div>
          ))}

          {tenantReports.length === 0 && (
             <div style={{ gridColumn: '1 / -1', padding: '3rem', textAlign: 'center', background: 'var(--bg-dark-card)', border: '1px solid var(--border)', borderRadius: '8px' }}>
                <FileText size={48} color="var(--text-muted)" style={{ margin: '0 auto 1rem auto' }} />
                <h3 style={{ fontSize: '1.2rem', color: 'var(--text-primary)' }}>No Reports Generated</h3>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Click "Generate Report" to create a new board summary.</p>
             </div>
          )}
        </div>

      </div>

      {/* Generate Dialog */}
      <Dialog open={isGenerateOpen} onClose={() => setIsGenerateOpen(false)} PaperProps={{ style: { background: 'var(--bg-dark)', color: 'var(--text-primary)', border: '1px solid var(--border)', minWidth: '400px' } }}>
        <DialogTitle style={{ borderBottom: '1px solid var(--border)' }}>Generate Board Report</DialogTitle>
        <DialogContent style={{ paddingTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>Report Title</label>
            <input 
              type="text" value={newReportName} onChange={(e) => setNewReportName(e.target.value)} placeholder="e.g. Q3 Resilience Report"
              style={{ width: '100%', padding: '0.75rem', background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: '4px', color: 'var(--text-primary)', outline: 'none' }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>Report Audience</label>
            <Select value={newReportType} onChange={(e) => setNewReportType(e.target.value as string)} fullWidth sx={{ background: 'var(--bg-card)', color: 'var(--text-primary)', '.MuiOutlinedInput-notchedOutline': { borderColor: 'var(--border)' } }}>
              <MenuItem value="Executive">Executive (High Level)</MenuItem>
              <MenuItem value="Operational">Operational (Deep Dive)</MenuItem>
              <MenuItem value="Regulatory">Regulatory (Compliance Focused)</MenuItem>
            </Select>
          </div>
        </DialogContent>
        <DialogActions style={{ borderTop: '1px solid var(--border)', padding: '1rem' }}>
          <button onClick={() => setIsGenerateOpen(false)} className="btn btn-outline">Cancel</button>
          <button onClick={handleGenerate} className="btn btn-primary">Generate</button>
        </DialogActions>
      </Dialog>

      {/* Schedule Dialog */}
      <Dialog open={isScheduleOpen} onClose={() => setIsScheduleOpen(false)} PaperProps={{ style: { background: 'var(--bg-dark)', color: 'var(--text-primary)', border: '1px solid var(--border)', minWidth: '400px' } }}>
        <DialogTitle style={{ borderBottom: '1px solid var(--border)' }}>Schedule Report Auto-Delivery</DialogTitle>
        <DialogContent style={{ paddingTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Configure automated delivery to board members or committees.</p>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>Frequency</label>
            <Select defaultValue="Monthly" fullWidth sx={{ background: 'var(--bg-card)', color: 'var(--text-primary)', '.MuiOutlinedInput-notchedOutline': { borderColor: 'var(--border)' } }}>
              <MenuItem value="Weekly">Weekly</MenuItem>
              <MenuItem value="Monthly">Monthly</MenuItem>
              <MenuItem value="Quarterly">Quarterly</MenuItem>
            </Select>
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>Recipients (Comma Separated)</label>
            <input 
              type="text" placeholder="board@acmeco.com"
              style={{ width: '100%', padding: '0.75rem', background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: '4px', color: 'var(--text-primary)', outline: 'none' }}
            />
          </div>
        </DialogContent>
        <DialogActions style={{ borderTop: '1px solid var(--border)', padding: '1rem' }}>
          <button onClick={() => setIsScheduleOpen(false)} className="btn btn-outline">Cancel</button>
          <button onClick={() => { setIsScheduleOpen(false); triggerToast('Schedule Created Successfully.'); }} className="btn btn-primary">Save Schedule</button>
        </DialogActions>
      </Dialog>

    </DashboardLayout>
  );
}
